name: fr_Florent59_LangueGaaranStrom
main: fr.Florent59.LangueGaaranStrom.Main
version: 1.12.2
description: Plugin cree pour le serveur GaaranStrom. Il permet au joueur de parler dans la langue locale du serveur et de n'etre compris que par les operateurs.
author: Florent59
commands:
 lgs:
  description: Permet de parler en langue locale.
 lfr:
  description: Permet de parler en langue commune.